# ===================================================================
# CONFIGURACIÓN GENERAL DE LA SIMULACIÓN


# NOTA: Se omitió 'simulation.seed' que viene en la guía del tutor para garantizar el flujo NO determinista solicitado.
simulation.totalSteps=100
simulation.arrivalBatchSize=5
tourists=50

# Frecuencia en pasos de ejecución para mostrar el estado en el Monitor
monitoring.intervalSteps=10
# Control de vehículos del parque (Fallas y mantenimiento)
vehicles.count=5
vehicles.repairSteps=3


# PERSONAL (Trabajadores)
workers.guards=3
workers.technicians=2
workers.dailySalary=150.0


# DINOSAURIOS DEL PARQUE 
dinosaurs.carnivores=5
dinosaurs.herbivores=15

# CONFIGURACIÓN POR ZONAS DEL PARQUE

# 1. Lugar de Arribo de Turistas
arrival.maxCapacity=30
arrival.ticketPrice=25.0

# 2. Recinto Central (Hub)
hub.souvenirPrice=15.0
hub.souvenirPurchaseProbability=0.4

# 3. Baños y SPA
bathroom.maxCapacity=10
bathroom.useDurationSteps=3
bathroom.spaPrice=20.0
bathroom.spaPurchaseProbability=0.2

# 4. Planta de Energía
powerplant.initialEnergy=100.0
powerplant.consumptionPerStep=1.5
powerplant.failureProbability=0.05
powerplant.maintenanceCost=200.0
powerplant.repairCost=500.0

# 5. Recintos de Observación (Experiencias)
enclosure.basic.maxVisitors=20
enclosure.basic.entryFee=10.0

enclosure.premium.maxVisitors=12
enclosure.premium.entryFee=30.0

enclosure.vip.maxVisitors=5
enclosure.vip.entryFee=75.0


# RUTAS DE SALIDA
output.directory=output